config/routes.rb
Rails.application.routes.draw do
  root 'chatrooms#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :messages, only: [:create]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  has_many :messages, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def validate_user_logged_in
    unless logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :validate_user_logged_in

  def index
    @message = Message.new
    @messages = Message.last(20)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :validate_user_logged_in

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", modified_message: message_render(message)
      head :no_content
    end
  end

  private

  def message_params
    params.require(:messages).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, if: :logged_in?, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You are now logged in"
      redirect_to root_path
    else
      flash.now[:error] = 'Wrong login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You are now logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    flash[:error] = "You are already logged in"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="orange circular coffee icon"></i>
  <span>Say Something</span>
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_with scope: :messages, class: 'ui reply form', url: messages_path, method: "POST", remote: true do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, id: "messages_body", placeholder: "Enter a message..." %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a href="" class="active item">
            Users Online
          </a>
          <a href="" class="item">
            Messages
          </a>
          <a href="" class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
<div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'Chatroom', root_path, class: "item" %>
<%= link_to 'Messages', root_path, class: "item" %>
<div class="right menu">
  <div class="ui dropdown item">
    Account
    <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to 'Log out', logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to 'Log in', login_path, class: "item" %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="item">
      <div class="ui primary button">
        <%= link_to 'Log in', login_path, class: "no-color" %>
      </div>
    </div>
  <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui inverted small menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username%></em>: <%= message.body %>
    </div>
  </div>
</div>